### ISSUE TITLE
BRDF metadata is ugly

### ISSUE THREAD

**Issue by uchchwhash** [OpenDataCubePipelines/tesp#61]
We need something like:

```
        brdf:
            dataset_ids: [...]
            model: definitive # one case to rule all ???
            alpha_1:
                band_1: <value>
                band_n: <value>
            alpha_2:
                band_1: <value>
                band_n: <value>
```
